baseURL = "https://AndrewDamico.github.io/CaseStudyGenerator/"
title   = "CaseStudyGenerator Docs"

[build]
  writeStats = true

[minify]
  disableXML = true

[module]
  [[module.imports]]
    path    = "github.com/bep/docuapi/v2"
    disable = false

theme = "docuapi"

[params]
  # Disable Prism.js— we’ll use Hugo’s built-in Chroma highlighter
  usePostCSS = false
  prism      = false

  search       = true
  maxMenuDepth = 3

  # Language tabs in code examples
  [[params.language_tabs]]
    key  = "go"
    name = "Go"
  [[params.language_tabs]]
    key  = "shell"
    name = "Shell"
  [[params.language_tabs]]
    key  = "python"
    name = "Python"

[languages]
  [languages.en]
    languageName = "English"
    weight       = 2
    title        = "Case Study Generator"
    [languages.en.params]
      toc_footers = [
        "<a href='#'>Sign Up for a Developer Key</a>",
        "Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
        "Hugo Theme by [bep](https://github.com/bep)",
      ]

  [languages.nn]
    languageName = "Latinum"
    weight       = 1
    title        = "DocuAPI-døme"

[markup]
  # Goldmark settings
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
      unsafe = true

  # Chroma highlighter settings
  [markup.highlight]
    codeFences  = true        # Highlight triple-backtick fences
    guessSyntax = false       # Use the specified fence language
    noClasses   = true        # Inline styles so no external CSS needed
    #style       = "dracula"   # <-- Change this to any Chroma style (e.g., monokai, solarized-dark, github, etc.)
    #style       = "gruvbox" #i like it!
    #style       = "github"
    #style       = "solarized-dark"
    #style      = "solarized-light"
    #style       = "monokai" #wow green
    #style       = "material" #boring
    #style       = "catppuccin-mocha" 
    #style = "rrt"
    #style = "vim"
    style = "vulcan"
    lineNos     = false       # Set to true to show line numbers

